### PR TITLE
GEO Investigation Context Product Scrub

### PR DESCRIPTION
**Pull request by jennifergward**
First round of investigation context product scrub by GEO.

## 🗒️ Summary
22 investigation context products scrubbed. Added associated documents for long descriptions, using Anne's model.

Per "[Context Product Work Log](https://docs.google.com/spreadsheets/d/1IaWQnVplSzwWlr2wyG9MeehOoSw5nuzMzptUkaOvLxw/edit?usp=drive_link)" assignments:
ATM to review Phoenix
SBN and IMG to review Viking

## ⚙️ Test Data and/or Report
N/A

## ♻️ Related Issues
N/A

### CODE REVIEW

**Review by lylehuber — CHANGES_REQUESTED** [review]
Suggest PHX instead of phx for <alternate_id>.

**Comment by jennifergward** [comment]
That's a good point. Are aliases case sensitive?

**Comment by lylehuber** [comment]
Pretty sure they are.

**Comment by jordanpadams** [comment]
@jennifergward @lylehuber Being as explicit as we possibly can be with this metadata, including proper capitalization, is ideal. The primary reason being a consumer of this metadata, like a software program or user interface, has no way of knowing how that abbreviation should be capitalized. For many, it is straightforward (MSL, PHX, MPF, etc.), but for many others it is not (OSIRIS-REx).

**Review by jordanpadams — APPROVED** [review]
Merging these initial updates

**Comment by jordanpadams** [comment]
@jennifergward I converted all the word docs to markdown, updated the filenames to include version numbers, and updated the labels. we can always come back to this, but merging so we can get these online.

**Pull request merged**
