### PR TITLE
RMS updates to Investigation context products #1

### PR DESCRIPTION
**Pull request by matthewtiscareno**
## 🗒️ Summary
This is the first round of Investigation context product updates from the RMS Node.

### CODE REVIEW

**Comment by matthewtiscareno** [comment]
Regarding the HST context product, we have noticed that there are three distinct versions of the Description:
1) The version that was historically in the context product, which is found in v1.1
2) The version in v1.2, which was truncated to only the first paragraph of the previous
3) The version in the [draft webpage](https://pds.mcp.nasa.gov/portal/investigations/urn--nasa--pds--context--investigation--mission---hst/overview)

In our v1.3 of the context product, we have synthesized by adding the best parts of the webpage's description to the v1.2 description.  We would like to discuss whether there is any home for the later paragraphs of the v1.1 description.

**Comment by matthewtiscareno** [comment]
For all three of the context products edited so far in this round version 1.1 ([1](https://github.com/NASA-PDS/EdWG/blob/main/data/pds4/context-pds4/investigation/mission.hst_1.1.xml), [2](https://github.com/NASA-PDS/EdWG/blob/main/data/pds4/context-pds4/investigation/mission.saturn_ring_plane_crossing_1995_1.1.xml), [3](https://github.com/NASA-PDS/EdWG/blob/main/data/pds4/context-pds4/investigation/mission.saturn_small_satellite_astrometry_1.1.xml)) contains a much longer Description that should be preserved somewhere.

**Comment by matthewtiscareno** [comment]
Regarding HST, we have noticed that the Description in v1.2 of the context product is quite different from the version in the [draft webpage](https://pds.mcp.nasa.gov/portal/investigations/urn--nasa--pds--context--investigation--mission---hst/overview)

In our v1.3 of the context product, we have synthesized by adding the best parts of the webpage's description to the v1.2 description.  However, we are curious about where the webpage description came from.

**Comment by matthewtiscareno** [comment]
Still to do:
1) Rescue the PDS3 context product `urn:nasa:pds:context_pds3:investigation:mission.saturn_occultation_of_28_sagittarius_1989`
2) Participate in updating the context products on which we are listed as contributors: namely Cassini and Juno (lead node: ATM), and Galileo and Voyager (lead node: PPI).  Hey @jmafi and @lylehuber, anything yet to discuss regarding these?

**Comment by jordanpadams** [comment]
@matthewtiscareno 

> Regarding HST, we have noticed that the Description in v1.2 of the context product is quite different from the version in the [draft webpage](https://pds.mcp.nasa.gov/portal/investigations/urn--nasa--pds--context--investigation--mission---hst/overview)
> 
> In our v1.3 of the context product, we have synthesized by adding the best parts of the webpage's description to the v1.2 description. However, we are curious about where the webpage description came from.

This is a known confusion with the current portal design: https://github.com/NASA-PDS/web-modernization/issues/245

That is actually displaying the description for the HST Instrument Host NOT the Investigation description. Both are supposed to be captured on this portal page, but that is not currently occurring. We introduced some refinements to this design at our last WMWG meeting (include both Investigation and Instrument Host descriptions on the same tab, with links to "deep dive" pages with more information), but that has yet to be implemented.

**Comment by matthewtiscareno** [comment]
> when updating the labels in the "working" directories for this exercise, there is no need to create new versions of the products

I understand the point.  But the thing is that the version that you have put into the working directory has some substantial changes from the previous version, and I might want to make changes upon those changes.  We can talk about the best way to bookkeep this, but in order to keep track of whose version is whose, I thought a version increment might make sense. 

Maybe the best thing to say at this point is that I'll fold my version into yours once we have come to consensus.

**Comment by matthewtiscareno** [comment]
Following up after discussion: I see @jordanpadams's point and have merged my versions into the pre-existing versions created by EN in the `working` directory.

**Comment by matthewtiscareno** [comment]
Hey @jordanpadams and EN team:  Please note [this commit](https://github.com/NASA-PDS/EdWG/pull/49/commits/d76930532f2bb6cd680698b1341f25891271e85f), in which I copied (without changing) the file `mission_SATURN_OCCULTATION_OF_28_SAGITTARIUS_1989_1.0.xml` from the `context-pds3` directory into the `working` directory, and also created v1.1 of the same (with fixed filename including lowercase letters and a `.` between `mission` and `saturn`). 

We went ahead and rewrote the description to conform with this effort.  However, the other tasks that you all did to the other context products have not been done here.  Would this be our job, or can we toss that task to you?

**Comment by jordanpadams** [comment]
@matthewtiscareno we can give the other updates a shot. thanks!

**Comment by jordanpadams** [comment]
@rchenatjpl for this context product update effort, @matthewtiscareno migrated the "SATURN OCCULTATION OF 28 SAGITTARIUS 1989" mission from our PDS3 context holdings to PDS4, but it will also need some of the telescopes migrated as well (or the PDS4 equivalents identified). Can you help us with that?

urn:nasa:pds:context_pds3:instrument_host:earth-based.eso1m
urn:nasa:pds:context_pds3:instrument_host:earth-based.eso22m
urn:nasa:pds:context_pds3:instrument_host:earth-based.lick1m
urn:nasa:pds:context_pds3:instrument_host:earth-based.pal200

**Comment by rchenatjpl** [comment]
I think so. Let me look

**Comment by jordanpadams** [comment]
@matthewtiscareno FYI, I removed the old PDS3 context product from the branch since I think it is more confusing having it there. We also already have a copy of that PDS3-migrated version out there in our system bundle.

I also went ahead and migrated the label from the Product_Mission_PDS3 to Product_Context and the appropriate mods to support. Let me know if I missed anything.

**Comment by rchenatjpl** [comment]
PDS3 insthosts got (properly) split up into facility and telescope in PDS4.

> urn:nasa:pds:context_pds3:instrument_host:earth-based.eso1m
This one exists already:
  urn:nasa:pds:context:facility:observatory.eso-la_silla
  urn:nasa:pds:context:telescope:eso-la_silla.1m04
I assume you’ll also need to map the context_pds3 instrument
  urn:nasa:pds:context_pds3:instrument:apph.eso1m
The only 2 instruments defined so far at the PDS4 telescope are
  urn:nasa:pds:context:instrument:eso-la_silla.1m04.denis
  urn:nasa:pds:context:instrument:multi-host.generic_insp_hsp
The latter is probably correct. Should I ask someone who may know better, e.g. Lynn? I.e. are these two the same:
  https://pds.nasa.gov/data/pds4/context-pds3/instrument/Product/inst_APPH__ESO1M.xml
  https://pds.nasa.gov/data/pds4/context-pds4/instrument/multi-host.generic_insp_hsp_1.0.xml

> urn:nasa:pds:context_pds3:instrument_host:earth-based.eso22m
This also already exists. Same facility as above, different telescope
  urn:nasa:pds:context:facility:observatory.eso-la_silla
  urn:nasa:pds:context:telescope:eso-la_silla.2m2
The one instrument in the context_pds3 product:
  urn:nasa:pds:context_pds3:instrument:apph.eso22m
probably also maps to
  urn:nasa:pds:context:instrument:multi-host.generic_insp_hsp
> urn:nasa:pds:context_pds3:instrument_host:earth-based.lick1m
The facility already exists as a PDS4 context product
  urn:nasa:pds:context:facility:observatory.lick
but the 1meter telescope does not. Shall I create it? They’d be
  urn:nasa:pds:context:facility:observatory.lick.nickel1m
The two context_pds3 instruments are:
  urn:nasa:pds:context_pds3:instrument:ccdc.lick1m
  urn:nasa:pds:context_pds3:instrument:hsccd.lick1m
These would be harder to map. It looks like people can attach their own instruments to this telescope, and I can’t easily tell if the two above are still there (https://mthamilton.ucolick.org/techdocs/telescopes/Nickel/intro/)
If there’s time pressure, I would just translate the two context_pds3 to
  urn:nasa:pds:context:instrument:lick.nickel1m.ccdc 
  urn:nasa:pds:context:instrument:lick.nickel1m.hsccd

> urn:nasa:pds:context_pds3:instrument_host:earth-based.pal200
  urn:nasa:pds:context:facility:observatory.palomar
  urn:nasa:pds:context:telescope:palomar.hale_5m08
The 1 context_pds3 instrument in the pds3 insthost is:
  urn:nasa:pds:context_pds3:instrument:circ.pal200
which has no pds4 equivalent yet. There’s a fair chance the camera’s been replaced. I would probably translate the existing product to:
  urn:nasa:pds:context:instrument:palomar.hale_5m08.circ
“CIRC” is pretty general (Cassegrain infrared camera), but I don’t know enough to pick a better ID

**Comment by rchenatjpl** [comment]
```These PDS3 insthosts got (properly) split up into facility and telescope in PDS4.
> urn:nasa:pds:context_pds3:instrument_host:earth-based.eso1m
This one exists already:
  urn:nasa:pds:context:facility:observatory.eso-la_silla
  urn:nasa:pds:context:telescope:eso-la_silla.1m04
I assume you’ll also need to map the context_pds3 instrument
  urn:nasa:pds:context_pds3:instrument:apph.eso1m 
The only 2 instruments defined so far at the PDS4 telescope are
  urn:nasa:pds:context:instrument:eso-la_silla.1m04.denis
  urn:nasa:pds:context:instrument:multi-host.generic_insp_hsp
The latter is probably correct. Should I ask someone who may know better, e.g. Lynn? I.e. are these two the same:
  https://pds.nasa.gov/data/pds4/context-pds3/instrument/Product/inst_APPH__ESO1M.xml
  https://pds.nasa.gov/data/pds4/context-pds4/instrument/multi-host.generic_insp_hsp_1.0.xml

> urn:nasa:pds:context_pds3:instrument_host:earth-based.eso22m
This also already exists. Same facility as above, different telescope
  urn:nasa:pds:context:facility:observatory.eso-la_silla
  urn:nasa:pds:context:telescope:eso-la_silla.2m2
The one instrument in the context_pds3 product:
  urn:nasa:pds:context_pds3:instrument:apph.eso22m
probably also maps to
  urn:nasa:pds:context:instrument:multi-host.generic_insp_hsp
> urn:nasa:pds:context_pds3:instrument_host:earth-based.lick1m
The facility already exists as a PDS4 context product
  urn:nasa:pds:context:facility:observatory.lick
but the 1meter telescope does not. Shall I create it? They’d be
  urn:nasa:pds:context:facility:observatory.lick.nickel1m
The two context_pds3 instruments are:
  urn:nasa:pds:context_pds3:instrument:ccdc.lick1m
  urn:nasa:pds:context_pds3:instrument:hsccd.lick1m
These would be harder to map. It looks like people can attach their own instruments to this telescope, and I can’t easily tell if the two above are still there (https://mthamilton.ucolick.org/techdocs/telescopes/Nickel/intro/)
If there’s time pressure, I would just translate the two context_pds3 to
  urn:nasa:pds:context:instrument:lick.nickel1m.ccdc 
  urn:nasa:pds:context:instrument:lick.nickel1m.hsccd

> urn:nasa:pds:context_pds3:instrument_host:earth-based.pal200
This already exists:
  urn:nasa:pds:context:facility:observatory.palomar
  urn:nasa:pds:context:telescope:palomar.hale_5m08 
The 1 context_pds3 instrument in the pds3 insthost is:
  urn:nasa:pds:context_pds3:instrument:circ.pal200
which has no pds4 equivalent yet. There’s a fair chance the camera’s been replaced. I would probably translate the existing product to:
  urn:nasa:pds:context:instrument:palomar.hale_5m08.circ
“CIRC” is pretty general (Cassegrain infrared camera), but I don’t know enough to pick a better ID```

**Comment by jordanpadams** [comment]
@rchenatjpl 

> > urn:nasa:pds:context_pds3:instrument_host:earth-based.lick1m
> The facility already exists as a PDS4 context product
>   urn:nasa:pds:context:facility:observatory.lick
> but the 1meter telescope does not. Shall I create it? They’d be
>   urn:nasa:pds:context:facility:observatory.lick.nickel1m
> The two context_pds3 instruments are:
>   urn:nasa:pds:context_pds3:instrument:ccdc.lick1m
>   urn:nasa:pds:context_pds3:instrument:hsccd.lick1m
> These would be harder to map. It looks like people can attach their own instruments to this telescope, and I can’t easily tell if the two above are still there (https://mthamilton.ucolick.org/techdocs/telescopes/Nickel/intro/)
> If there’s time pressure, I would just translate the two context_pds3 to
>   urn:nasa:pds:context:instrument:lick.nickel1m.ccdc 
>   urn:nasa:pds:context:instrument:lick.nickel1m.hsccd

Yes. Let's create the 1m telescope and the associated instruments if you can? Not a super time crunch here, but would like to have this information tracked. If you are concerned it is not accurate, then let's punt on the instruments for now and we can try to figure out who the experts on that would be to give us info.

> > urn:nasa:pds:context_pds3:instrument_host:earth-based.pal200
> This already exists:
>   urn:nasa:pds:context:facility:observatory.palomar
>   urn:nasa:pds:context:telescope:palomar.hale_5m08 
> The 1 context_pds3 instrument in the pds3 insthost is:
>   urn:nasa:pds:context_pds3:instrument:circ.pal200
> which has no pds4 equivalent yet. There’s a fair chance the camera’s been replaced. I would probably translate the existing product to:
>   urn:nasa:pds:context:instrument:palomar.hale_5m08.circ
> “CIRC” is pretty general (Cassegrain infrared camera), but I don’t know enough to pick a better ID

Copy that. If we could get an instrument context product, that would be awesome.

**Comment by matthewtiscareno** [comment]
I appreciate you working on this, @rchenatjpl.  To some extent, the questions you are asking will be the purview of whoever does the work of migrating this data set to PDS4, which has not happened yet.  Since this a bare context product without (as yet) any PDS4 data to point to it, I suggest you might make your best stab and not worry too much about the details.

**Comment by matthewtiscareno** [comment]
@jordanpadams, thank you for updating the 28 Sgr context product. Here are some items I noticed:
- The `Identification_Area.name` and `Investigation.name` are both still in all caps.  In fact, this is true for many context products.  Should we fix these?
- I see that the LID contains `observing_campaign` rather than `mission`, which is fine.  Should we then change the filename to reflect that?
- Speaking of having `observing_campaign` in the LID, it would be great if the context products for saturn_small_satellite_astrometry and saturn_ring_plane_crossing_1995 could have LIDs that correspond in this way.  These data sets have not been migrated to PDS4, so these context products were created prematurely and could be seen to fall under the policy in 6D.3.1 of the Standards Reference that allows multiple drafts before solidifying one as v1.0

**Comment by matthewtiscareno** [comment]
I believe @jordanpadams wants me to merge this PR, so I'll go ahead and do that.  The items identified in my last message can be addressed later.

**Comment by jordanpadams** [comment]
@matthewtiscareno 

> The Identification_Area.name and Investigation.name are both still in all caps. In fact, this is true for many context products. Should we fix these?

Yes. I should have probably done that but ran onto other tasks. Not super critical right now.

> I see that the LID contains observing_campaign rather than mission, which is fine. Should we then change the filename to reflect that?

@rchenatjpl thoughts?

> Speaking of having observing_campaign in the LID, it would be great if the context products for saturn_small_satellite_astrometry and saturn_ring_plane_crossing_1995 could have LIDs that correspond in this way. These data sets have not been migrated to PDS4, so these context products were created prematurely and could be seen to fall under the policy in 6D.3.1 of the Standards Reference that allows multiple drafts before solidifying one as v1.0

@rchenatjpl thoughts? I am OK with changing these.

**Pull request merged**
